apiVersion: apps/v1
kind: Deployment
metadata:
  name: clash-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clash
  template:
    metadata:
      labels:
        app: clash
    spec:
      containers:
        - name: clash
          image: "{{ registry }}/{{ org }}/mihomo:{{ meta_tag }}"
          env:
            - name: SUBSCRIBE_URL
              value: "{{ subscribe_url }}"
          ports:
            - containerPort: 7890
            - containerPort: 9090
          volumeMounts:
            - mountPath: /etc/timezone
              readOnly: true
              name: timezone-volume
            - mountPath: /etc/localtime
              readOnly: true
              name: localtime-volume
      volumes:
        - name: timezone-volume
          hostPath:
            path: /etc/timezone
        - name: localtime-volume
          hostPath:
            path: /etc/localtime

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: metacubexd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metacubexd
  template:
    metadata:
      labels:
        app: metacubexd
    spec:
      containers:
        - name: metacubexd
          image: "{{ registry }}/metacubex/metacubexd"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/timezone
              readOnly: true
              name: timezone-volume
            - mountPath: /etc/localtime
              readOnly: true
              name: localtime-volume
      volumes:
        - name: timezone-volume
          hostPath:
            path: /etc/timezone
        - name: localtime-volume
          hostPath:
            path: /etc/localtime

---

# 如果需要对外暴露服务，还需要为每个服务创建Service资源
apiVersion: v1
kind: Service
metadata:
  name: clash-service
spec:
  selector:
    app: clash
  ports:
    - name: tcp-7890
      port: 7890
      protocol: TCP
      targetPort: 7890
    - name: udp-7890
      port: 7890
      protocol: UDP
      targetPort: 7890
    - name: http-9090
      port: 9090
      protocol: TCP
      targetPort: 9090
  type: ClusterIP
  externalIPs:
    - 10.0.1.116
---
apiVersion: v1
kind: Service
metadata:
  name: metacubexd-service
spec:
  selector:
    app: metacubexd
  ports:
    - name: http-28002
      protocol: TCP
      port: 28002
      targetPort: 80
  type: ClusterIP
  externalIPs:
    - 10.0.1.116